baseurl: ""
url: "https://www.alonsoespinosa.com"
repository: alauriela/alonsoespinosa-web   
timezone: Europe/Madrid
future: false

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

paginate: 5
paginate_path: "/blog/page:num/"

permalink: /:title/
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: /blog/:title/
